services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./src/data:/config
    ports:
      - 80:80
    restart: unless-stopped
